### ISSUE TITLE
How is “Never start a line with ( or [” ment?

### ISSUE THREAD

**Issue by ausi** [feross/standard#110]
“Never start a line with `(` or `[`” is a very simple rule, but I’m not sure it means the right thing.

`standard` doesn’t generate errors for code like this:

```js
foo(
  (1 + 2) * 3,
  [1, 2, 3]
)
```

Is this a bug in `standard` or is starting a line with `(` or `[` allowed in this case?

If it is allowed, shouldn’t it say “Never start a **statement** with `(` or `[`”?

**Comment by feross** [comment]
I think that saying "never start a line" is actually more accurate than "never start a statement", though both are actually incorrect.

The correct rule is "`\n` ends a statement unless the next line starts with `[`, `(`, and a few addition, uncommon binary operators."

Instead of writing all that, I added a [longer explanation](https://github.com/feross/standard/blob/master/RULES.md#automatic-semicolon-insertion-asi) to RULES.md and linked it from the list of rules in README.md.
