### ISSUE TITLE
Starting lines with slashes

### ISSUE THREAD

**Issue by ausi** [feross/standard#111]
The readme says starting a line with `(` or `[` is the only gotcha with omitting semicolons, but what about starting lines with `/` e.g. with a regular expression? The following code breaks:

```js
var foo = function () {}
var bar = 'baz'

/baz/.test(bar) && foo(bar)
```

`standard` detects the error and writes `Unexpected token .`, but there are cases where `standard` isn’t able to detect such errors, e.g.:

```js
var foo = function () {}
var bar = 'baz'

/ bar(')/.test(/' / +bar) && foo(bar)
```

`standard` doesn’t find an error but the code breaks with `undefined is not a function`.

Omitting semicolons would be nice, but how can I make sure I’m not falling into such ASI edge cases?

**Comment by mattdesl** [comment]
*Personally* I feel the following should be disallowed at the beginning of a line:

```
+ * / - ` , . 
```

They almost always appear in one-liners and clever shorthand (as in your example) that would be better suited inside an `if` statement.

Whereas `(` and `[` should produce errors unless preceded by a semicolon, for legitimate use cases like this: [standard#80](https://github.com/feross/standard/issues/80)

Two eslint issues that seem to be holding some of these things back:
https://github.com/eslint/eslint/issues/1983
https://github.com/eslint/eslint/issues/746

**Comment by yoshuawuyts** [comment]
Not sure if it's currently disallowed, but I sometimes like to do:
```js
function (arg1, arg2, arg3) {
  return 'https://'
    + arg1
    + '/somethingverylongthatdoesntfitononeline'
    + arg2
    + '/'
    + arg3
}
```
alternatively it could be written as:
```js
function (arg1, arg2, arg3) {
  let ret = 'https://'
  ret += arg1
  ret += '/somethingverylongthatdoesntfitononeline'
  ret += arg2
  ret += '/'
  ret += arg3
  return ret
}
```
I feel the second one is a bit clunkier, but don't feel strongly about it.

**Comment by mattdesl** [comment]
This is all about starting *statements* with ASI-breaking characters, so both of your examples should be fine.

The wording should be more explicit as pointed out here:
https://github.com/feross/standard/issues/110

**Comment by feross** [comment]
While, it would be nice to throw an error on these less-common ASI-breaking cases, I don't want to add additional checks beyond what `eslint` supports. So, let's move the discussion there. Here's a thread where some of these ideas are being discussed: https://github.com/eslint/eslint/issues/746.

Once eslint supports the rules we need, I'm happy to enable them to make this catch more of these edge cases. In the meantime, `standard` will just miss these cases. Sorry, no tool is perfect.

**Comment by dcousens** [comment]
@feross I know this issue needs to be fixed upstream.  But maybe we can keep the issue open until then?  Closing this gives the impression its fixed IMHO.

**Comment by feross** [comment]
Okay, so there's been progress on this front! :+1: 

As @mattdesl originally suggested, the most troublesome operators `+ * / -` are now forbidden at the beginning of a line, with the [operator-linebreak](http://eslint.org/docs/rules/operator-linebreak) rule. So (mostly as an accident) @ausi's second example is now caught by `standard` because the last line starts with a `/`.

```js
var foo = function () {}
var bar = 'baz'

/ bar(')/.test(/' / + bar) && foo(bar)
```

I also enabled the new [no-unexpected-multiline](http://eslint.org/docs/rules/no-unexpected-multiline) rule, which attempts to ensure that "two unrelated consecutive lines are not accidentally interpreted as a single expression".

Other variations are also caught now:

```js
var foo = function () {}
var bar = 'baz'

(/ bar(')/).test(/' / + bar) && foo(bar)
```

If you find additional gotchas, please [file an eslint issue](https://github.com/eslint/eslint/issues/new).

I think this issue can finally be closed.
