### ISSUE TITLE
Expose eslint's "checkstyle" output format through command line switch

### ISSUE THREAD

**Issue by lvillani** [feross/standard#142]
`eslint` can print its output in Checkstyle format which is extremely useful to integrate `standard` with editors/IDEs, since parsing it is more robust than stylish' format.

Since `standard` is based on `eslint` it would be nice to expose this feature from standard's command line.

**Comment by lunaryorn** [comment]
:+1:

**Comment by feross** [comment]
So far editors haven't had any issues integrating using the current format. A simple regex will do the trick. I'd prefer to keep the number of command line flags in this module to the bare minimum so I'm going to close this. If this actually blocks an editor from adding support, I'm happy to reconsider.

**Comment by dcousens** [comment]
@lvillani did you have an editor in mind where this would make your life easier? (I assume you might be looking to writing a plugin maybe?)

**Comment by lvillani** [comment]
@dcousens I opened the bug report based on a request from @lunaryorn but then proceeded to implement a pattern recogniser. I'm not sure whether this change is still needed, though.

**Comment by lunaryorn** [comment]
@feross How can you reasonably claim that there were no issues with integrating the current format in editors?  You didn't write all these integrations, did you?  How do you know what issues actually occurred?  And what is this issue, if not an issue with “integrating the current format in editors”?  

I maintain Flycheck, which supports about 70 tools for various languages.  For you, it's just a “simple regex”.  For me, it's about 50 different regexps, which I have to understand and maintain, and constantly fix, because writing linters is apparently all about changing the output format with every new release to add just another pointless fancy new thingy.

One regexp is simple.  50 regexps are an incredibly brittle and a countless source of problems.  Regexps just don't scale.

**Comment by feross** [comment]
@lunaryorn I didn't write all the integrations, but I've read several of them. A regex as simple as [this](https://github.com/Flet/SublimeLinter-contrib-standard/blob/master/linter.py#L25) will do the trick :)

I understand that you don't want to maintain a bunch of changing regexes – that sounds painful. However, the output format of standard is **locked** – it will never change. So assuming the regex you wrote for standard is correct, it will never stop working and you will never need to change it.
