### ISSUE TITLE
speed issues (standard 3.11.0)

### ISSUE THREAD

**Issue by gr2m** [feross/standard#144]
Here's a simple change in our code that brings down `standard` execution time down from 16s to 1s. https://github.com/hoodiehq/pouchdb-hoodie-api/commit/3aefb7c170f4694e3f7dc8b0bddb36375b820ab3

Instead of ignoring the dist/ and docs/ folders, we instead pass the blobs for files we want to be checked. Both should have the same effect, but the difference in time execution is 1600%. Any idea what could cause this? Are we doing it wrong:tm: ?

**Comment by feross** [comment]
Yeah, I noticed this slowdown before too. See issue: https://github.com/feross/standard/issues/130

Your opening this issue prompted me to finally run `git bisect` and figure this out. Turns out this innocent change in v3.7.0 was the root cause: https://github.com/feross/standard/commit/04fe0efecb39d300dc8ee106ab4348ab8f8e3d8d

By reverting this change, standard is now 12.6x faster to run! (1.79s vs 22.59s over the [webtorrent](https://github.com/feross/webtorrent) codebase)

Published as 3.11.1.

**Comment by gr2m** [comment]
fuckyeah! That's fantastic news! Thanks Feross!!

btw, talking about "standards", I think you'll love https://www.npmjs.com/package/semantic-release very much. Once you start using it, you won't look back (just like `standard` form me :) ). Happy to help with the setup. And if you don't like it, drinks on me :beers: :cocktail:
