### ISSUE TITLE
Global return statements fail

### ISSUE THREAD

**Issue by watson** [feross/standard#167]
If I read #148 correctly, this should already be fixed and on npm, but given the following code in the file foo.js it fails anyway:

```js
var n = Math.random()
if (n > 0.5) return console.log('You won the lottery!')
console.log('No luck - try again')
```

Standard will fail with the error "Illegal return statement":

```
$ standard --version
4.3.1
$ standard
standard: Use JavaScript Standard Style (https://github.com/feross/standard)
  /tmp/foo.js:2:20: Illegal return statement
```

So, help me out here :) What's going on?

**Comment by feross** [comment]
eslint (what `standard` uses under the hood for error checking) doesn't both support ES6 module syntax *and* global return statements at the same time. It's super annoying. We added module syntax support somewhere in the v3 series and lost global return support then. Right now, we've opted to support the module syntax instead of global return, as you can see in #148.

But, since we now have support for custom js parsers now, perhaps we can remove module support and add back global return support. Users can get module support by using the esprima-fb or babel-eslint custom parsers.

What do folks think?

**Comment by dcousens** [comment]
Undecided.  Sounds like user-land configuration to me.

**Comment by watson** [comment]
Just to clarify my use case: Some of my modules (like [git-att](https://github.com/watson/git-att/blob/91087aff4bb54aa2002819db9492b86c9065e0cb/index.js#L17) referenced in this PR) ships with command line scripts (`bin` in package.json) and here it's really convenient to use global returns to abort under certain circumstances.

**Comment by feross** [comment]
@watson Understood - I like to do that in my code too. Here's a workaround, if you're interested in one:

```js
if (argv.version || argv.v) {
  version()
  process.exit(0)
}
```

**Comment by feross** [comment]
@dcousens Yeah, I get what you're saying. Maybe we should just make `standard` use babel-eslint for broader ES6 and ES7 support? I wonder if that parser supports global return...

**Comment by dcousens** [comment]
That could be worth looking into.
Out of interest,  would the desired behaviour with ES6 modules be that if an `export` is detected, global `return` should fail?

My understanding is that `return (undefined)` doesn't make sense in a module setting because of `export`s that may have been previous defined?

**Comment by watson** [comment]
@feross Yeah, I usually also do that - but when calling an async function it doesn't help: https://github.com/watson/tweetcat/blob/4b287496b4a2d6dbcc22c495d1e071a9366242f3/bin.js#L25

**Comment by feross** [comment]
Using `babel-eslint` won't solve the problem. `babel` doesn't support top-level return either.

https://github.com/babel/babel/issues/1298

**Comment by feross** [comment]
I think this issue is unlikely to be fixed since global returns aren't valid ecmascript (which is silly). The various teams that work on the parsers are unwilling to add a special rule for invalid ecmascript.

Unless anyone can think of something clever, I'm going to close this issue as WONTFIX.

**Comment by dcousens** [comment]
I'm thinking `WONTFIX` is suitable.  To clarify, the final position is that any `globalReturn` shall be invalid, ES5 or not?

**Comment by feross** [comment]
@dcousens That's correct. `standard` doesn't distinguish between ES5 or ES6 right now so there's no easy way to allow it for just ES5.
