### ISSUE TITLE
yoda expressions

### ISSUE THREAD

**Issue by nichdiekuh** [feross/standard#175]
Hi,

I was wanted to apply the standard rules on my codebase, but then I hit the yoda rule and felt strongly discouraged. Are there any strong arguments against using yoda expressions?
I can get the rid of semicolons and everything, but for some reason I'm struggeling to give up on yoda expressions. 
Is it possible to add an exception for this case?

**Comment by feross** [comment]
Yoda expressions are less readable because they're backwards from how an english sentence works. You can read more at the eslint [rule page](http://eslint.org/docs/rules/yoda).

If you really want, you can fork `standard` and change the rule. Or, you can use the [eslint shareable config](https://github.com/feross/eslint-config-standard) and `.eslintrc` to customize the rules:

```json
{
  "extends": ["standard", "standard-react"],
  "rules": {
    "yoda": 0
  }
}
```

But really, the point of `standard` is to eliminate these types of style discussions. If you care so strongly about one rule, `standard` might not be for you.

**Comment by nichdiekuh** [comment]
I see your point, thank you for the explanation!

**Comment by feross** [comment]
No problem!

**Comment by dcousens** [comment]
@nichdiekuh remembering, the biggest positive over a yoda expression is avoiding the `if (myVar = "something")` mistake.
This mistake is already caught by other rules in `standard` IIRC.

**Comment by feross** [comment]
@dcousens Yep, you're correct.
