### ISSUE TITLE
Repeated arguments fail

### ISSUE THREAD

**Issue by dcousens** [feross/standard#199]
Almost definitely an eslint bug,  just filing it here.

``` javascript
function fun () {}

// expected Error about the missing space, instead it just fails and dies
fun(function(err, _, _, what) {

})
```

**Comment by dcousens** [comment]
@feross could you confirm?  Then I'll file a bug in eslint.

**Comment by feross** [comment]
@dcousens confirmed

**Comment by feross** [comment]
Filed an issue: https://github.com/eslint/eslint/issues/3128

:)

**Comment by dcousens** [comment]
Thanks @feross, sorry.

**Comment by feross** [comment]
@dcousens No worries.

It turns out this is expected behavior whenever eslint encounters a "parse error". We can attempt to convince the eslint team to treat errors like this as non-fatal so the rest of the errors will show up. But this may take a while for them to fix, so I don't think we need to track it here. Interested folk can follow the eslint bug here: https://github.com/eslint/eslint/issues/3128
