### ISSUE TITLE
5.2 breaks ternary operator style

### ISSUE THREAD

**Issue by julien-f** [feross/standard#246]
All my code suddenly failed to pass standard due to a change in standard 5.2 concerning the ternary operator:

```js
const a = true ?
  1 :
  2
```

```
standard: Use JavaScript Standard Style (https://github.com/feross/standard)
  index.js:1:17: '?' should be placed at the beginning of the line.
  index.js:2:6: ':' should be placed at the beginning of the line.
```

**Comment by feross** [comment]
The ternary (`?` `:`) and the 'blocks must not be padded' rules have been part of `standard` even though they haven't been enforced consistently due to eslint bugs and ditching jscs at one point. We temporarily lost enforcement of this rule. But now that we can enforce them again, this is basically bugfix, so it went out in a minor, not major version.

Sorry that this broke your tests -- hopefully this won't happen again. I don't think we have any more of these types of changes to release. See https://github.com/feross/standard/issues/248 for more discussion.

**Comment by julien-f** [comment]
Understood, thanks.

**Comment by timdp** [comment]
Just wondering what the reasoning behind this is. For example:

```js
var foo = (bar === 'test')
  ? baz()
  : quux()
```

If you don't look at lines 2 and 3, you don't know that `foo` will be assigned either `baz()` or `quux()`. Instead, it looks like the statement ends there and `foo` is a boolean.

My personal preference would be:

```js
var foo = (bar === 'test') ?
  baz() :
  quux()
```

which bears a lot of similarity to e.g.

```js
var foo = bar + 'test' +
  baz() +
  quux()
```

(You could obviously put everything on one line, but imagine longer statements ...)
