### ISSUE TITLE
strict mode

### ISSUE THREAD

**Issue by sonnyp** [feross/standard#287]
Couldn't find a discussion on the topic.

What's the logic behind not enforcing strict mode in standard?

**Comment by marvinroger** [comment]
Knowing that Node ^4.0.0 requires strict mode to be able to use the new ES6 `let`, `const` keywords, function-in-blocks and classes.

**Comment by rstacruz** [comment]
My guess is so that you can check for snippets of a file, but I don't know enough about the project's history to make an authoritative comment.

**Comment by yoshuawuyts** [comment]
`standard` already warns for strict-mode incompatible syntax. ES6 already has strict mode enabled by default. I think that between the two, enforcing the `"strict mode"` pragma at the top of every file should be left up to the authors.

Also: enforcing the pragma would break a ton of packages using `standard`.

**Comment by feross** [comment]
Right, what @yoshuawuyts said.

`standard` already assumes that your code is running in an ES6 environment, so you'll warnings for things that are strict-mode incompatible. But enforcing `"use strict"` is going too far, since it doesn't meaningfully change the way code runs for the vast majority of `standard` users.

If you need node support, just add "use strict" to your files.
