### ISSUE TITLE
Never start a line with ` because of tagged template strings

### ISSUE THREAD

**Issue by gyson** [feross/standard#289]
because

```js
let x = () => {}

`hello`

console.log(x)
```

will output 

```
undefined
```

(tested with nodejs v4.1.0)

**Comment by rstacruz** [comment]
Reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/template_strings#Tagged_template_strings

**Comment by feross** [comment]
Issue opened on eslint: https://github.com/eslint/eslint/issues/4169

**Comment by feross** [comment]
Turns out this is a bug in V8. See the bug I filed here: https://code.google.com/p/v8/issues/detail?id=4497

A semicolon should automatically be inserted by the JS engine. The fact that it isn't in node v4 is a bug. Fortunately, the V8 developers say it's fixed in `master` so it'll make it's way to node soon enough.

Mystery solved.

**Comment by gyson** [comment]
Thanks for your clarification.

Just one more question:

Would this case
```js
let x = () => {}
let y = x
`hello`
```
be parsed to
```js
let x = () => {};
let y = x`hello`;
```
or
```js
let x = () => {};
let y = x;
`hello`;
```
?

**Comment by feross** [comment]
@gyson I think it will actually be parsed to the first one. :( Fortunately, the eslint developers are aware and plan to improve the rule: https://github.com/eslint/eslint/issues/4169#issuecomment-149064446

**Comment by gyson** [comment]
@feross I see. Thanks.
