### ISSUE TITLE
Warn about Test FW's '.only' calls

### ISSUE THREAD

**Issue by taromero** [feross/standard#313]
Just hit a case where I merged a test case forgetting to remove Mocha's `.only` from one of the suites, resulting in CI nor running all of the tests before merging.

The rule would look for either `describe.only`, `context.only` or `it.only`.

It would be nice to detect this. Let me know if it doesn't make much sense.

It seems like there's not an option on raw `eslint`, but there's a plugin for this: https://github.com/lo1tuma/eslint-plugin-mocha/blob/master/docs/rules/no-exclusive-tests.md.

**Comment by feross** [comment]
Thanks for opening this issue. I see why you would want to catch a stray `.only` in your mocha tests.

I'm not in favor of adding mocha-specific rules to `standard`. This issue has come in the past when users asked to define `describe`, `it`, etc. as globals. The reason is that lots of people use other test frameworks and we don't want to make assumptions about what tools they're using, or tie standard to mocha in an unhealthy way.

There's already a project [mocha-standard](https://www.npmjs.com/package/mocha-standard) that might be open to the idea of [extending standard](https://www.npmjs.com/package/eslint-config-standard) and adding mocha-specific rules.

**Comment by taromero** [comment]
I understand completely, thanks for the quick reply and for pointing to those resources!
