### ISSUE TITLE
/**/*.js file matching issue in package.json

### ISSUE THREAD

**Issue by digitalsadhu** [feross/standard#320]
I can't work this out and it may well not be anything to do with standard but I can run:

```
./node_modules/.bin/standard server/**/*.js
```

And detect errors in server/index.js

However the exact same command when run from npm script detects no errors in server/index.js

```js
...
"lint": "./node_modules/.bin/standard server/**/*.js",
...
```

**Comment by feross** [comment]
What version of `standard` are you running? You can check with `standard --version`. If you're not running the latest (5.4.1), you should update. 

Pretty sure that this bug was fixed a long time ago.

---

 Also, unrelated, but you can simplify your npm run scripts by omitting `./node_modules/./bin` since `npm run` automatically adds everything in that folder to your path. So this would do the same thing:

```
...
"lint": "standard server/**/*.js",
...
```
