### ISSUE TITLE
Should not allow space before bracket notation

### ISSUE THREAD

**Issue by mattdesl** [feross/standard#389]
I just got bit by a small bug because the linting didn't catch it. Might be worth disallowing this, I can't see any reason it should be legit.

```js
setup('shims argv', 'argv.js', JSON.stringify([
  path.resolve(__dirname, 'fixtures', 'argv.js'),
  '--foobar'
]) [ '--foobar' ])
  ^
  Error is here, missing a comma
```

It wouldn't catch the same code if there was no space, but at least when a space is there (i.e. in the case of a missing comma) it could be caught early.

Thoughts? :smile:

**Comment by yoshuawuyts** [comment]
I agree it looks like a bug. It might be worth filing this on [eslint](https://github.com/eslint/eslint).

**Comment by kaicataldo** [comment]
Wait, are you sure this is incorrect syntax? It might just be because it's late, but I'm not seeing the error...I don't know the particulars of the specific example, but it looks like valid syntax to me:

`function1('string', 'string', function2([object.method(var, 'string', 'string'), 'string'])['property of function 2']);`

**Comment by feross** [comment]
@kaicataldo Even though it's technically valid syntax, I think @mattdesl was hoping standard would report it as error, because property accesses shouldn't have spaces after them. So it's either inconsistent style, or a programmer error.

Happy to enable a rule for this, if it's available in `eslint`.

**Comment by feross** [comment]
Doesn't look like there's an eslint rule for this.

**Comment by feross** [comment]
@mattdesl Are you interested in opening an issue on eslint to request this rule?

**Comment by mattdesl** [comment]
It is such a minor thing that I can't really be bothered. 😁 Thanks for looking tho.

**Comment by feross** [comment]
I think we can actually catch this with the http://eslint.org/docs/2.0.0/rules/no-whitespace-before-property rule. Will ship this in `standard` v6.
