### ISSUE TITLE
Trailing Comma 

### ISSUE THREAD

**Issue by aakashsigdel** [feross/standard#400]
It would be good if there was a rule for ending a object entry with comma. 

```js
  let abc = {
    def: 'xyz',
    ghi: 'mno',
}
```
This would be helpful as we won't accidentally forget to add a comma before adding a new property while editing the object later in time.

**Comment by feross** [comment]
Sorry, we can't even consider this change because it would break 100% of the packages that use `standard` today.

If you're using `standard`, you can't even make this error, because it's invalid JavaScript, so you'll get a parse error when you run the tool, and probably the first time you try to run your app.

**Comment by garex** [comment]
Standards should respect comma-first rule.

Then this feature will not be needed:

```
var magicWords = [ 'abracadabra'
                 , 'gesundheit'
                 , 'ventrilo'
                 ]
  , spells = { 'fireball' : function () { setOnFire() }
             , 'water' : function () { putOut() }
             }
  , a = 1
  , b = 'abc'
  , etc
  , somethingElse
```

**Comment by feross** [comment]
@garex Sorry, no.

**Comment by channprj** [comment]
How can I turn it off temporarily?

**Comment by feross** [comment]
@channprj See https://standardjs.com/#how-do-i-hide-a-certain-warning

**Comment by lehelk** [comment]
Ok, I can understand the need for a standard/set of rules to follow and once setting these rules to not deviate from them. It feels like this specific rule was pushed due to IE8 & below bug. This should also not be an issue when using compilers. I would really appreciate knowing the reasoning behind this choice.

**Comment by qqtrend** [comment]
Is there a way to change this project-wide? (Because we are blessed with not having to support IE8 ever again, and don't want ugly diffs, not even in the name of standards!)

This works if put at the top of each js file:

```
 /* eslint comma-dangle: ["error", "always-multiline"] */
```

But each of these package.json edits were ignored: (the "babel-eslint" config is working; I left that in these examples to show I am editing the correct part of package.json)

```
  "standard": {
    "parser": "babel-eslint"
  },
  "eslintConfig": {
    "rules":{
      "comma-dangle": ["error", "always-multiline"]
    }
  },
```

and

```
  "standard": {
    "parser": "babel-eslint",
    "rules":{
      "comma-dangle": ["error", "always-multiline"]
    }
  },
```

For completeness, I also tried:

```
  "standard": {
    "parser": "babel-eslint",
    "eslintConfig": {
      "rules":{
      "comma-dangle": ["error", "always-multiline"]
      }
    }
  },
```

**Comment by LinusU** [comment]
@qqtrend you can use [standardx](https://github.com/standard/standardx)
