### ISSUE TITLE
glob pattern not working?

### ISSUE THREAD

**Issue by mehl321** [feross/standard#402]
I put this command in my package.json file: `"lint": "standard src/**/*.js*"` and when I run it the errors contained in my `src` subfolders are found but not those contained in the root of `src`.

How can I make this work everywhere?

**Comment by feross** [comment]
This is because your shell (`bash`, `zsh`, etc.) is expanding the double star `**` differently than how `standard` does it (using the `glob` npm package).

This shell expansion is happening automatically before `standard` gets invoked.

You can pass through the string unmodified by your shell if you do this:

```
"lint": "standard 'test/**/*.js*'"
```

(note the quotes around the glob)

Cheers!

**Comment by mehl321** [comment]
Fantastic! I didn't know this trick.
