### ISSUE TITLE
Better JSX handling

### ISSUE THREAD

**Issue by nickcolley** [feross/standard#415]
I love Standard but it falls down with JSX, is the project looking to be transparently opinionated like it is with the rest of JS, or is this something that'd need to be in a fork?

Things like https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-curly-spacing.md for example is a pain to not have consistent.

**Comment by yoshuawuyts** [comment]
Oh yeah, that rule seems reasonable, PR welcome!

Regarding JSX - I think the reason it's less thorough might be because there've been less contributions to JSX compared to other rules. We don't particularly have a policy regarding what is / isn't acceptable as a rule - it's determined on a case-by-case basis. If you run into anything that you think should be part of `standard`, open a PR and we'll be happy to review it. Cheers!

**Comment by nickcolley** [comment]
That's great to hear thanks for the quick reply, I'll open a PR at https://github.com/feross/eslint-config-standard-jsx

**Comment by feross** [comment]
The `jsx-curly-spacing` rule is already enabled with the following config:

```json
    "react/jsx-curly-spacing": [2, "never"]
```
