### ISSUE TITLE
Prevent callback in try block

### ISSUE THREAD

**Issue by LinusU** [feross/standard#423]
I misstake that I've seen quite a few people doing is calling a callback in a `try` block, not thinking about the fact that any error occurring in the callback will now be catched as well.

Example bad code:

```javascript
try {
  cb(null, JSON.parse(data))
} catch (err) {
  cb(err)
}
```

What the authors intent really was:

```javascript
let parsed
try {
  parsed = JSON.parse(data)
} catch (err) {
  return cb(err)
}

cb(null, parsed)
```

I understand that this might be a bit hard to implement, but I still think that it at the very least is worth discussing.

Would it be unreasonable to assume that every variable named `cb` is a callback? It seems to be the accepted practice to name it as such, in the same way that we have rules that assumes that variables named `err` are errors, and needs to be handled.

What do you think?

**Comment by dcousens** [comment]
`cb`, `next`,  `done`, `callback`, `fin`, `finish`, `free` ... I feel like this could go on forever.
I agree conceptually though :)

**Comment by feross** [comment]
Agree conceptually. The first step is to propose this in eslint. I'd prefer to not maintain our own rules, since that's a ton of work.

**Comment by feross** [comment]
I'm going to close this issue due to lack of progress.

This rule isn't really something that I, or any of the other `standard` collaborators that I know of, plan to implement at the moment. That's not to say it's a bad idea. I would accept a PR that enabled it, but the first step would be to get it added to ESLint or one of the ESLint plugins that we already depend on.

Then, send a PR to add the rule to `standard`, or open a new issue and I'm happy to do it.
