### ISSUE TITLE
Constantly getting 'irregular whitespace' when using ||

### ISSUE THREAD

**Issue by Cuel** [feross/standard#455]
Hi. I'm using Atom with this editorconfig

```
root = true
[*]
end_of_line = crlf
insert_final_newline = true
trim_trailing_whitespace = true
charset = utf-8
indent_style = space
indent_size = 2
```

.eslintrc
```
{
  "extends": ["standard"]
}
```

EDIT:
I'm not entirely sure when it happens. It seems to be when strings are involved, e.g this will always cause it
```javascript
let a = {raw: {channels: [{channel_name: 'test', cid: '979'}]}}
let root = a.raw.channels.find(v => v.channel_name === 'test' || v.cid === '979')
```

The above always results in `Irregular whitespace not allowed at line xx`
Happens on both Mac and Windows
The position is always just before the ||
I can fix it temporarly by going to the position, pressing backspace and space again.
It works until I open the file again. I'm not sure if this is a standard, eslint or atom issue.

Is this a known issue?

**Comment by feross** [comment]
I can't think of how this could be caused by `standard`.

It's worth noting that on OS X typing ALT+SPACE inserts a non-breaking space character (which looks the same as a space, but isn't a normal space). Maybe that's the issue?

No idea how the issue could come back when you re-open the file. Sounds like your editor is modifying files automatically when they're opened.

**Comment by Cuel** [comment]
It's not alt+space, that's for sure. I'm using editorconfig which is the only package capable of editing files when opened afaik. I'll keep looking

**Comment by LinusU** [comment]
You could open the file in a hex editor to see what got inserted
