### ISSUE TITLE
Trailing spaces inside a multi-line string

### ISSUE THREAD

**Issue by simonratner** [feross/standard#482]
The following triggers an error:
```javascript
let str = `
${a}
      <-- significant trailing whitespace
${b}
`
```

Current workaround is to surround the block with `/* eslint-disable no-trailing-space */`, but it would be better if whitespace inside strings was ignored for the purposes of this check.

**Comment by feross** [comment]
Reported this to ESLint: https://github.com/eslint/eslint/issues/5786

**Comment by LinusU** [comment]
Hmm, I don't know though, many people uses editors that trim trailing whitespace and I think that it might just be a very idea to force the author of the code to solve it in another way up front, rather than having the code break later when someone saves the file in e.g. Atom. If you really need trailing whitespace in the string you could write it as follows.

```javascript
let str = [
  '',
  a,
  '      ',
  b,
  ''
].join('\n')
```

**Comment by feross** [comment]
Yeah, I sort of agree with you @LinusU.

**Comment by simonratner** [comment]
Actually I agree, automatic trimming of trailing whitespace is common and will just cause problems later.
In my particular case, I need *any* whitespace, so `\t` is a solution that isn't too ugly, but in other cases something like your suggestion or even `${ '  ' }` will work in a template string.

**Comment by feross** [comment]
Okay, going to close this since it's reported to ESLint and they'll do with it what they will at this point.
