### ISSUE TITLE
Enforce final break

### ISSUE THREAD

**Issue by LinusU** [feross/standard#520]
Would it make sense to enforce a `break` even in the last `case` statement within a `switch`? I think it's a good practice so that the next guy doesn't forget to add one in.

```js
switch (_) {
  case 1:
    console.log('Hello')
    break
  case 2:
    console.log('world!')
    // standard would enforce a break here
}
```

**Comment by feross** [comment]
Sure I'm fine with that. But I don't think ESLint has a rule for it, so it's probably not worth the effort. If you get a rule or option for this into ESLint, happy to enable it :)

But it's really not a risk if you're using `standard` since it will warn about "fall through" when the next programmer adds a new `case` and forgets to add `break`.

**Comment by feross** [comment]
Going to close this since there's no ESLint rule for it. But feel free to send a PR when/if you get it added.
