### ISSUE TITLE
Require block comments to be balanced

### ISSUE THREAD

**Issue by feross** [feross/standard#572]
http://eslint.org/docs/rules/spaced-comment

This rule (which is already enabled in `standard`) has a new option to enforce "balanced" spacing in block comments.

For example, this would be an error:

```js
/* This is a block comment*/
```

It would be need to be rewritten like this:

```js
/* This is a block comment */
```

As part of this change, I propose that we remove the exceptions that allow the keywords "global", "global", "eslint", and "eslint-disable" to be used without a space:

```js
/*global myVar */
```

It's odd to enforce a space at the end while making it optional at the beginning for these keywords. With these exceptions removed, this is how these comments would need to be written:

```js
/* global myVar */
```

Eslint handles space or no-space versions of these directives without issue.

The number of affected repos is moderate (2%):

```
1..422
# tests 422
# pass  412
# fail  10
```

Thoughts?

**Comment by dcousens** [comment]
LGTM

**Comment by feross** [comment]
This will be included in standard v8

**Comment by Kovensky** [comment]
I kinda like being able to write eslint directives in a "style-violating" way (and wish I could do it with more of them, like `//eslint-disable-line`) because, if the directive has a typo, it will be flagged by the linter instead of just being ignored. OTOH, if you have a directive, it's because it's disabling or configuring specific rules, and if the directive was being ignored, you'd be getting warnings for the things it fixes...

**Comment by feross** [comment]
@Kovensky Interesting point. Your last point is correct. If the rule isn't getting picked up (due to a typo) then you'll get a warning because the rule you were trying to disable wasn't actually disabled.

I think this rule change is a good move since there were 2 ways to do something, and now there will be only one.
