### ISSUE TITLE
Maybe consider disallowing `jsx` extension?

### ISSUE THREAD

**Issue by capaj** [feross/standard#585]
I have read beautiful reasoning as to why it is not the best practice to name files with JSX `.jsx`, but instead `.js`: https://github.com/airbnb/javascript/pull/985#issuecomment-239145468

In my future projects I would prefer if I would not see `.jsx` files- do you think this is a rule standard could merge if I opened a PR for it? I guess there isn't an eslint rule for that, but maybe we could create one? Or maybe just use a simple glob expression?

**Comment by feross** [comment]
Seems like decent reasoning, but I don't feel this is super important. I do know that `standard` shouldn't automatically fail just because there are .jsx files in the folder you're linting.

We could consider only detecting .js files by default, instead .js and .jsx like we do now. This would slightly discourage usage of .jsx. People who use .jsx would have to change their command to `standard *.js *.jsx`. If we remove it (even in a major version) some users will still think their .jsx files are being checked when they're not, until they realize it much later.

Do other contributors have thoughts?

**Comment by feross** [comment]
I don't really see the benefit of stopping automatically checking .jsx files. It'll just trip up some users who use that extension. If you don't want to use .jsx, you can just use .js and standard works fine. And as mentioned before, we shouldn't actively *prevent* the usage of a certain extensions, IMO.
