### ISSUE TITLE
no-duplicate-imports rule triggered by `import type` statements

### ISSUE THREAD

**Issue by Gozala** [feross/standard#599]
Forking #592 to it's separate issue:

Standard uses 'no-duplicate-imports' rule which is triggered if there are two or more import statements from the same module.

It seems that this rule is also triggered for `import type` Flow statements, e.g. this results in an error:

``` js
import { foo } from 'someModule';
import type { Bar } from 'someModule';
```

There is no other way to combine these two statements into one import statement as flow want's to distinguish type and value imports.

I would really like this issue to be resolved to be able to use standard style with flow typed project.

**Comment by Gozala** [comment]
Here are some of the relevant issues:

Corresponding issue for babel-eslint:
https://github.com/babel/babel-eslint/issues/293

I also have proposed using [import/no-duplicates](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-duplicates.md) setting instead of stock `no-duplicates` as former seems to handle this case properly.

**Comment by feross** [comment]
You're using two non-standard things: babel and flow type annotations. This is life on the bleeding edge, nothing quite works... 😒 

That said, since I'm considering adding `eslint-plugin-import` in standard v9 (since it potentially catches lots of errors), this should get fixed for free if we use `import/no-duplicates` instead of `no-duplicates`.

**Comment by feross** [comment]
No ecosystem impact. This will be part of the standard v10 beta.
