### ISSUE TITLE
Cannot use /* exported */ to prevent no-unused-vars warnings

### ISSUE THREAD

**Issue by davidystephenson** [feross/standard#614]
I am writing javascript for use in a browser environment, without using node/webpack/browserify. I want to be able to use eslint's `exported` keyword to mark variables that will be used in other imported files. This keyword does not seem to be functioning currently.

**Comment by feross** [comment]
Interesting. I wasn't aware eslint had an `exported` keyword. Context here: https://github.com/eslint/eslint/issues/1200

This keyword won't work with `standard` because we enable the "node" eslint environment which makes eslint assume that all code is in a function scope.

I suggest using the recommendation from RULES.md, which is to explicitly use `window.*`. For example:

```js
window.MyExportedVar = function () { /* ... */ }
```
