### ISSUE TITLE
order of variable declaration is not taken into account.

### ISSUE THREAD

**Issue by kilianc** [feross/standard#636]
Not sure what rule is missing but this passes validation:

``` js
const b = a
const a = 5
```

**Comment by feross** [comment]
We currently do not enable the `no-use-before-define` rule because it triggers way too many false positives. Once [this eslint issue](https://github.com/eslint/eslint/issues/7111) is addressed, we can enable the rule so that issues like the one you encountered (as well as [this one](https://github.com/feross/standard/issues/615)) will be caught.

**Comment by LinusU** [comment]
This wasn't meant to be closed, right?

**Comment by dcousens** [comment]
I personally get bitten by this issue so often I've enabled it in my global `eslint-config-standard/eslintrc.json` :+1: 
But I can understand that people who use confusing variable ordering w/ closures would have issues with it.  (bias not obvious)

**Comment by feross** [comment]
@dcousens My plan is once/if that eslint bug gets fixed, enable the rule so that:

- using classes before they're defined is **not** allowed
- using function declarations before they're defined is allowed (hoisting)
- using variable declarations before they're defined is allowed, but prevented when it's clearly incorrect, e.g.

Not allowed:

```js
console.log(foo)
var foo = 5
```

Allowed:

```js
function printFoo() {
    console.log(foo)
}
var foo = 5
```

This is allowed since it *is* possible to use `printFoo()` correctly if you call it after `foo` is defined. And lots of users of `standard` do this.

When we start enforcing `let` over `var`, maybe we can tighten up this rule.

**Comment by dcousens** [comment]
I completely agree,  it makes recursive or circular functions completely impossible otherwise.
The example I more often run into that actually makes intuitive sense to me:

``` js
function foo (x) {
  return x ? bar(x) : 1
}

function bar (x) {
  return foo(x - 1)
}
```

No valid ordering exists with the rule as it standards AFAIK.
```

**Comment by dcousens** [comment]
Enabling `[2, "nofunc"]` locally again in a project I just found pointed out several issues that had gone unmissed in a refactoring... @feross IMHO this is a must.

**Comment by feross** [comment]
@dcousens Are you proposing we just enable the overly aggressive rule even before the eslint issue is addressed? We *could* do that, but I'm worried about the effect of all the warnings on valid code. We don't want users to think that pleasing `standard` is a lot of work. It's a tough balance to maintain.

**Comment by feross** [comment]
The issue at https://github.com/eslint/eslint/issues/7111 was just accepted by the team!

**Comment by dcousens** [comment]
@feross it was more of a notice for others whom might be waiting on https://github.com/eslint/eslint/issues/7111,  but wanted to increase safety in their own projects without being too aggressive.

**Comment by feross** [comment]
This was just merged. Let's include it in the standard v9 release :)

**Comment by feross** [comment]
This will be part of standard v9. No ecosystem impact.

**Comment by caesarsol** [comment]
Sorry, is this distinguishing between var and let/const? Doe the behaviour change in any way?

**Comment by feross** [comment]
This rule will prevent clearly wrong code, like:

```js
console.log(x)
const x = 5
```

But it will allow code like:

```js
function foo () {
  console.log(x)
}
const x = 5
foo()
```

Since it works fine :)
