### ISSUE TITLE
Support ES8 (ES 2017), in addition to ES7 (ES 2016)

### ISSUE THREAD

**Issue by jescalan** [feross/standard#645]
With the latest version of standard, this code produces an error, but is perfectly valid es6:

```js
async () => { console.log('hello') }
```

Maybe I'm doing something wrong here? I'd think someone else would have noticed this before...

**Comment by feross** [comment]
We support ES7 at the moment, but `async` actually is part of the ES8 spec.

(ESLint supports ES8, so we can try updating to that again. I only updated us to ES7 earlier this week since in ES8 mode, I ran into a parse bug that treated `async` as a reserved word which broke valid uses like `cb({ async: true })`. That was just fixed in `espree`, though.

I'll give this another shot.

**Comment by feross** [comment]
Okay, new version of `standard` just released that support ES8, including `async` and `await`. Enjoy!

8.3.0.

**Comment by feross** [comment]
https://twitter.com/feross/status/781564129303638018
