### ISSUE TITLE
support for different targets?

### ISSUE THREAD

**Issue by matthewmueller** [feross/standard#657]
Apologize if this is the wrong place for this – I'm not too familiar with standard/eslint's ecosystem.

Is there any way in either standard or one of the plugins to say something like this: I'd like to lint against node 4, a target that would error out if I try to destructure, regardless of what my node version actually is.

I'm thinking something along the lines of https://github.com/babel/babel-preset-env or autoprefixer.

**Comment by feross** [comment]
Right now, there's no way to configure `standard` to do something like that. There might be an eslint plugin for something like that, but I'm not aware of it.

I'm going to close this since it isn't an issue with `standard`, but if anyone else who is watching this repo has suggestions, feel free to be helpful!

**Comment by feross** [comment]
This
