### ISSUE TITLE
Referencing TypeScript definition files

### ISSUE THREAD

**Issue by krokofant** [feross/standard#660]
To use definition files for libraries to provide IntelliSense is increasing.

I'd like to be able to use this as acceptable by standard
`/// <reference path="jquery/index.d.ts" />`

Currently I get the

> Expected space or tab after '//' in com
> ment.

**Comment by feross** [comment]
Can you link to the documentation where this `///` is specified?

If it's sufficiently common, I'm fine adding an exception for this. We already have a few exceptions for other tooling.

**Comment by krokofant** [comment]
Here is the [TypeScript documentation](http://www.typescriptlang.org/docs/handbook/triple-slash-directives.html) for the `///` syntax.

**Comment by yoshuawuyts** [comment]
@feross which exceptions do you refer to? iirc in hindsight the sentiment wasn't entirely favor of non-standard additions to standard, even though it's been a huge drive in standard's adoption

I feel that if this were to become a rule, it should be strict; e.g. only allow it for a leading comment on the first line - disabling it in its entirety might be undesireable

**Comment by krokofant** [comment]
To add more to my opinion I want to use standard as it is a simple ruleset to adhere to but it's not usable if it hinders, and provides no alternative, to something that a developer sees as necessary. Regarding the format I just want *something* that works. 😄

**Comment by feross** [comment]
@yoshuawuyts You can see the list of exceptions to the [`spaced-comment`](http://eslint.org/docs/rules/spaced-comment) rule here: https://github.com/feross/eslint-config-standard/blob/5eed6cd11bc77866fe719ee117918d0570e3a71c/eslintrc.json#L141

The point of `spaced-comment` is to prevent `//my comment` in favor of `// my comment`. The chance that a user's comment begins with a `/` is basically nil:

```
// /is this a possible legit comment?
```

So, IMO, we should just allow it, especially if it's a directive used by popular tools. We already allow:

```
//! This comment will not be removed by minifiers
/*! This comment will not be removed by minifiers */
```

Note, a space is still required after the `//!` because the `!` is considered a "marker" that is part of the start of the comment string. So `//!comment` is still disallowed.

**Comment by yoshuawuyts** [comment]
@feross fair point, ACK on this change

**Comment by feross** [comment]
Okay, adding this to the `standard` v9 milestone.

**Comment by feross** [comment]
This will be part of standard v9. Since this relaxes a rule, there is no ecosystem impact.
