### ISSUE TITLE
--fix doesn't deal with curly even spacing

### ISSUE THREAD

**Issue by cyberwombat** [feross/standard#677]
The following gets flagged for inconsistent spacing:
   
    {{ foo: 'bar'}}

But `--fix` does not fix it.

**Comment by saadq** [comment]
That's because currently both styles of spacing are allowed:

    {foo: 'bar'} // ok
    { foo: 'bar' } // ok

The only thing that isn't allowed is when it's inconsistent like in the example you have up there. I believe that eventually only one of these will be allowed, but it hasn't been decided on which one. There's an ongoing issue about it [here](https://github.com/feross/eslint-config-standard/issues/35).

**Comment by feross** [comment]
Yep, what @saadq said.
