### ISSUE TITLE
(generators) Missing space before *

### ISSUE THREAD

**Issue by elf-pavlik** [feross/standard#683]
[function* - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function*)

I think should not generate warning about missing space before `*` in declaration of generator function.

**Comment by saadq** [comment]
The whitespace part doesn't really matter, it's just personal preference. Any of these would work fine:

```js
function* name() {

}

function *name() {

}

function * name() {

}
```

feross mentioned [here](https://github.com/feross/standard/issues/568#issuecomment-233450323) that enforcing the whitespace around the `*` is intentional to make it stand out from a normal function.

**Comment by elf-pavlik** [comment]
Thanks, I tired searching for 'genrators' before creating issue but that closed issue didn't show up :(

Maybe worth adding that rule to http://standardjs.com/rules.html ?
