### ISSUE TITLE
Custom ecmaVersion

### ISSUE THREAD

**Issue by fanatid** [feross/standard#687]
It is possible to set custom `ecmaVersion` in `standard` section in `package.json`? I want write package on ES5 and see error from standard if any feature from new ecma versions will be used.

**Comment by feross** [comment]
I am hesitant to add any additional configuration to `standard`, beyond what we already support. If you want to customize standard, I recommend extending the eslint shared config.

**Comment by dcposch** [comment]
I think this would be useful, too.

If you're running a project that needs to work everywhere without no transpiler, then you want the linter to tell you if you accidentally used an ES6 feature somewhere.

**Comment by dcposch** [comment]
For example, if you want to write a library that can run anywhere: in node, in the browser, in a web worker, then you could use

```
standard --env=builtin --ecmaVersion=5
```

...to make sure you're not using any Node globals (eg `process`), browser globals (eg `window`), or ES6 features (eg `let`).

**Comment by feross** [comment]
Re-opening for discussion.

**Comment by feross** [comment]
This is a cool idea but I think that we're rapidly approaching a world where we'll just start shipping ES6 and even ES7 directly to browsers, since support has gotten really good.

For example, take a look at how much support a feature like `const` has. [97%](http://caniuse.com/#feat=const). Even super recent features like async functions already has [54% support](http://caniuse.com/#feat=async-functions), and that'll probably be 75% in a few months as Safari and Edge users continue upgrading to the latest version.

Also, we'll maybe eventually do a plugin system (without config!) (discussed in another issue) so that you can do `npm install standard standard-es5 && standard` and standard will run with extra rules to force only ES5. This seems like a better approach than adding options to `standard`.
