### ISSUE TITLE
Unnecessary escape character apparently

### ISSUE THREAD

**Issue by dcousens** [feross/standard#704]
```
Unnecessary escape character: \]. (no-useless-escape)
```

The regex:
``` js
/Expected property "1" of type \[Buffer\], got String "foobar"/
```

Is this one for eslint? Or am I misunderstanding?

**edit:**  This apparently works... is it even sane though? It feels so odd.
``` js
/Expected property "1" of type \[Buffer], got String "foobar"/
```

**Comment by dcousens** [comment]
This only started happening in a recent update.

**Comment by feross** [comment]
The `no-useless-escape` rule got stricter in the latest version of eslint. I think they're right that it's technically useless to escape `]` but I agree that this is a tad bit aggressive.

This might be the source of the issue: https://github.com/eslint/eslint/issues/7424

Could you open an issue on the ESLint repo?

**Comment by feross** [comment]
One good argument for why ESLint should not warn about `\]` is that regex's "Unicode mode" (which @mathiasbynens recently described as "strict mode" for regex literals) doesn't warn about it.

`/\a/u` - throws because `a` is **always** an invalid escape sequence. Prevents user from making a mistake.
`/\)/u` - does not throw even though `)` does not need to be escaped. This is because `)` sometimes does need to be escaped, and it doesn't hurt to just allow it. Very unlikely this is a user mistake.

This let's users keep things nice and parallel in their regex, like: `/\[Buffer\]/u`. My opinion: if it's good enough for regex "Unicode mode", then it's good enough for ESLint. 👍

**Comment by feross** [comment]
I opened an issue: https://github.com/eslint/eslint/issues/7656

**Comment by dcousens** [comment]
Thanks for championing this @feross

**Comment by feross** [comment]
Sure. If they end up adding a way to specify exceptions to this rule, we can open a new issue for that.

**Comment by feross** [comment]
FYI, the original eslint issue was fixed: https://github.com/eslint/eslint/issues/7656
