### ISSUE TITLE
Why we don't just use .editorconfig

### ISSUE THREAD

**Issue by GGYaX** [feross/standard#732]
No need the comple xml configuration, it's works for other IDE.

**Comment by feross** [comment]
I'm not very familiar with `.editorconfig`, but it doesn't offer [very many rules](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties), it seems.

`standard` currently has [at least 150 rules](https://github.com/feross/eslint-config-standard/blob/master/eslintrc.json), including many that involve parsing the AST of the code in order to check for possible errors. This is, to my knowledge, beyond the scope of what `.editorconfig` can do.

**Comment by wesleytodd** [comment]
I think the idea here is not "fully supporting standard rules", it is that a few small things can be made easier on users who have to conform to multiple projects guidelines.  So for example, the following file will nicely set my vim settings so a `tab` defaults to two spaces in my standard compliant projects, despite defaulting my editor to use tab characters normally:

```
# http://editorconfig.org
root = true

[*]
indent_size = 2
indent_style = space
```

Which is handy for people like me who use both `happiness` and `standard` on different projects.

**Comment by feross** [comment]
@wesleytodd Thanks for explaining further. I don't see what's stopping you from adding an .editorconfig to your project though. I don't think it's the place of `standard` to add files to your project.

**Comment by wesleytodd** [comment]
Oh maybe I also miss-understood the OP.  I actually ended up here because I was going to copy the `.editorconfig` for this project into mine :)  But didn't find one, and searched issues.  So my assumption was that the OP here was asking why not add an `.editorconfig` to this project.  Anyway, looks like I was wrong.

**Comment by GGYaX** [comment]
My idea was not about the rule. As I see in `standard.xml` in [webstorm configuration](https://github.com/feross/standard/blob/master/docs/webstorm.md), it can easily replaced by .editorconfig. And It can also be extended to other IDE.

**Comment by feross** [comment]
Ah, I see. I'm happy to accept a PR that adds an `.editorconfig` file to the repo. Cheers.
