### ISSUE TITLE
Misleading name

### ISSUE THREAD

**Issue by phpnode** [feross/standard#83]
Hello, the style you're proposing here is not *standard*, in fact some of your guidelines are downright controversial, e.g. the semicolon stuff. Calling it `standard` is both arrogant and misleading, why not call it `one-true.js` or similar? At least then it's clear that it's an *opinion*.

**Comment by callumacrae** [comment]
> arrogant and misleading

Dude, really? That's not constructive.

You can't convince someone to change something by insulting them.

**Comment by tomcartwrightuk** [comment]
There has been some discussion on this already - see https://github.com/feross/standard/issues/78.

**Comment by phpnode** [comment]
@callumacrae `arrogant and misleading` is not an insult, it's just a statement of fact. Labelling your own preference as "standard" when the reality is anything but *is* arrogant, and it *is* misleading.

**Comment by jprichardson** [comment]
>  in fact some of your guidelines are downright controversial

Indeed. Positive change can cause controversy. The utility provided by `standard` outweighs the concern for any controversy. I'd go so far to say that if you're work doesn't cause controversy, then people just don't care enough and the impact of your work upon the world may be negligible.

> arrogant and misleading is not an insult, it's just a statement of fact

It is possible to make a statement that is simultaneously factual and insulting. For instance, telling someone that they're obese may be both a fact and insulting. Regardless, your claim of arrogance isn't a fact unless you revise it say "I find it arrogant" as your current claim implies that *all* people find it arrogant, which is not a fact.

The name `standard` is an adequate name. In fact, I quite like it. Admittedly, I'm biased since I agree with most of the stylistic choices. It wasn't always that way though! But what I'm really excited about is the impact that `standard` will have upon the ecosystem.

**Comment by maxogden** [comment]
http://neversaw.us/2015/03/24/thoughtlessness/
