### ISSUE TITLE
Change "parsing error" to "reserved word not allowed" when naming a function "delete"

### ISSUE THREAD

**Issue by rbecheras** [feross/standard#835]
When we name a function `delete`, standard find a `parsing error`.

Here an example in atom editor with the plugin [`linter-js-standard`](https://github.com/ricardofbarros/linter-js-standard):

![capture d ecran de 2017-04-04 14-17-42](https://cloud.githubusercontent.com/assets/6469390/24656160/a054e92e-1941-11e7-950a-ffe4be847982.png)

I would suggest using a more semantic error name/type/description. Something like 

> Function naming error: 'delete' is a native reserved word

**Comment by feross** [comment]
Thanks for the suggestion. I wish that we could show a friendlier error, but in this case the usage of the token `delete` is literally crashing the JS parser, since it's not expecting a reserved word to be used in that location.

I don't think there's an easy solution that `standard` can apply here, since this error originates in ESLint. If you feel strongly that this should be improved, consider opening an issue on the ESLint issue tracker. https://github.com/eslint/eslint
