### ISSUE TITLE
Adding file extensions to lint by default

### ISSUE THREAD

**Issue by KC-SI** [feross/standard#845]
By running `node_modules/standard/bin/cmd.js` it only lints *.js and *.jsx as the usage information says. How would I add more file extensions, such as .ts so that it would be linted as well. Currently I use `node_modules/standard/bin/cmd.js */**/*.ts`. While there is nothing wrong with this, is it possible to add the file extension to package.json?

**Comment by feross** [comment]
You should only need to use `standard **/*.ts`. You don't need the extra `*/` in front. If you're having issues, try quoting the argument so that your shell won't expand the stars. You want them to get passed into `standard`.

To answer your question: There is no way to add this to the `"standard"` field in package.json. It must be passed in as a command line argument.

Pro-tip: If you are using npm scripts, you do not need to use the full path `node_modules/standard/bin/cmd.js`. Instead just use `standard` and your local copy will be used automatically. Like this:

```json
{
  "scripts": {
    "test": "standard **/*.ts"`
  }
}
```
