### ISSUE TITLE
Parentheses for arrow function aruments

### ISSUE THREAD

**Issue by fanatid** [feross/standard#853]
Probably this question was already raised, sorry if this issue is duplicate.

Right now all this expression are valid:
```js
const fn1 = () => {}
const fn2 = (a) => {}
const fn3 = a => {}
const fn4 = (a, b) => {}
```

When we have exactly one argument, parentheses can be or not be. Will some of this expression standardize in standard? Or two expression will be always valid?

**Comment by feross** [comment]
This is a tough one. We tried enforcing "always use parens around arrow function arguments" but had to revert it since omitting parens is quite a popular style.

This was discussed in https://github.com/feross/standard/issues/309, https://github.com/feross/standard/issues/414, and https://github.com/feross/eslint-config-standard/pull/63 if you want to dig into the historical discussion.

**Comment by feross** [comment]
Feel free to continue discussing here, but I'm closing this since I don't expect we'll make any changes anytime soon around this rule.
