### ISSUE TITLE
Unexpected indentation for Lodash method body inside JSX

### ISSUE THREAD

**Issue by broadhu2** [feross/standard#857]
I ran `standard --fix` and there seems to be an issue with indentation inside a JSX block that uses a lodash method. Screenshot shows code before running `standard --fix` on the left and after on the right.

![standard fix issue](https://cloud.githubusercontent.com/assets/9254892/24971877/138e2e80-1f7f-11e7-8dc5-680d91f3e4ad.PNG)

Can you explain why this happens?

**Comment by feross** [comment]
`standard` requires that you use spaces for indentation, not tabs. When you ran `standard --fix` most of the indentation was replaced by spaces, but it looks like it failed to indent the code inside the JSX block correctly. It left tabs (represented by arrows) on the first and last lines of the JSX block, but replaced the inner line's tabs with spaces (represented by dots).

This is a bug in ESLint's `indent` rule. However, ESLint just finished a brand-new rewritten `indent` rule that will be part of ESLint 4.0.0. However, that version is still in alpha at this time. This will be fixed in a future version of `standard` when we update to ESLint 4.0.0.

You can follow this issue to know when this is fixed in `standard`: https://github.com/feross/standard/issues/735
