### ISSUE TITLE
Move package config into config property

### ISSUE THREAD

**Issue by jhabdas** [feross/standard#860]
https://standardjs.com/#how-do-i-ignore-files

Docs suggest using `pkg.standard` to configure standard. I'd like to hear thoughts on moving these into `pkg.config.standard` section ([example](https://github.com/jhabdas/fetch-inject/blob/d080c981f8b6b6cbf843fe35c71bc947344884b8/package.json#L51-L58)), updating the docs to only recommend the new location and leaving in backwards compatibility for those who've already started using `pkg.standard`.

**Comment by feross** [comment]
What's the rationale? It's common to use the top-level of `package.json` to do configuration.

**Comment by jhabdas** [comment]
> What's the rationale?

Scoping, mostly, for better manifest organization. Brings the added benefit anyone needing to use `standard` in the package manifest for another purpose has an escape hatch to do so.

**Comment by tunnckoCore** [comment]
it's better for sure. couple of other tools uses it, and evryone should use it

**Comment by LinusU** [comment]
`config` is used by npm to define config that the user of a package can set to affect that package. The example that they show is putting `port` inside so that the user can control the port with `npm config set foo:port 8001` [(ref)](https://docs.npmjs.com/files/package.json#config)

I think it would be weird to include standard stuff under that since it would give the assumption that you should be able to configure it with `npm config set` which currently isn't possible. It would also be weird to be able to use `npm config set` since the standard config should be the same for everyone working on the project, that's the entire idea with the standard...

> couple of other tools uses it, and evryone should use it

which tools are using it?

**Comment by jhabdas** [comment]
@LinusU thanks for dropping the 411. here are two, and it looks like `ghook` is on the way out and doing something super weird: https://github.com/jhabdas/fetch-inject/blob/d080c981f8b6b6cbf843fe35c71bc947344884b8/package.json#L51-L58 but whatevs.

**Comment by tunnckoCore** [comment]
> I had no idea NPM defined that.

me too.

> @LinusU: which tools are using it?

Commitizen for example. But your explanation make sense to me too.

**Comment by jhabdas** [comment]
I'm going to drop this. If someone else wants to take the torch please backlink.
