### ISSUE TITLE
How to use standard in conjunction with eslint-config-standard-react

### ISSUE THREAD

**Issue by mrchief** [feross/standard#885]
How does one use standard in conjunction with eslint-config-standard-react? Add eslintrc and extend it with eslint-config-standard-react? Isn't that going against the philosophy of standard (no config, no eslintrc)? 

Its dupe of https://github.com/feross/standard-react/issues/13 but hoping it'll get an answer here.

**Comment by Flet** [comment]
Yes, it would have to be done using `eslint` directly instead of `standard` itself.

Take a look at [standard's eslintrc file](https://github.com/feross/standard/blob/master/eslintrc.json) for a sample of how to do this. Just be sure to `npm install` all the eslint configs you're referencing and use `eslint` to run linting.

Closing this issue, but feel free to respond!

**Comment by feross** [comment]
For now, the only way to use that config is to set up eslint yourself. It didn't make sense to force React rules on everyone since there are actually lots of frameworks that use JSX these days besides React and it was causing trouble for those users.

There are some proposals for how to enable using little add-on rule sets that I've been thinking about, but none implemented yet.
