### ISSUE TITLE
Remove undefined checks

### ISSUE THREAD

**Issue by jprichardson** [feross/standard#9]
This breaks on global variables, specifically mocha tests (`it` and `describe`). As mentioned here https://github.com/feross/standard/commit/91e8a4183b513dd4f276f7095f7d46c6032c7dfe your `jshint` checks are overzealous and defeat the purpose of this module, which states that it's for style checking.

**Comment by feross** [comment]
This is why mocha's implicit globals are a bad idea! ;) But jokes aside, thanks for pointing out that this is an issue. I'd like JavaScript Standard Style to work out-of-the-box even when people are using mocha, and would like it to work for you!

So, a couple of options to solve this:

- Add `it` and `describe` to the [globals](https://github.com/feross/standard/blob/master/lib/.jshintrc#L9) section of `.jshintrc`. This solves the immediate issue.

- Remove the check for undefined variables. I'm less excited about this solution because catching undefined variables actually helps find bugs, dead code, and typos. For example, it uncovered [this dead code](https://github.com/feross/bittorrent-tracker/commit/ebb86f728fe986140ef050a4a7faa42aaa41e25a#diff-78c12f5adc1848d13b1c6f07055d996eL188) in `bittorrent-tracker` (`socket` is undefined) which would have been a runtime error if it weren't wrapped in a try-catch by chance.

I'm curious why you think reporting unused variables isn't a style issue - could you elaborate?

**Comment by feross** [comment]
Here's another example where this option saves the day:

```js
function test () {
  var myVar = 'Hello, World'
  console.log(myvar) // Oops, typo here - would be a runtime error, but caught by `standard`
}
```

**Comment by feross** [comment]
Actually, that last example would be caught by the `undef` option, even if we disabled the `unused` option.

`undef`: prevent using a variable that was never defined. Ex: `myvar` is used, but never undefined.
`unused`: prevent defined a variable and never using it. Ex: `myVar` is defined, but never used.

**Comment by feross** [comment]
Okay, I remove the `unused` rule, but kept the `undef` rule in place.

Defining a variable and never using it, while confusing, isn’t going to cause break at runtime like the reverse case (using an variable that was never defined) will.

Cheers!

**Comment by dcousens** [comment]
Sounds good :+1:

**Comment by dcousens** [comment]
I think this the best approach, relaxing the `undef` rule opens up to a **lot** of bugs which I am/was hoping to catch using this standard in my tests (I already run jshint to catch all these locally).

**Comment by dcousens** [comment]
Personally, I actually feel `unused` could have stayed, if your local tests are tied directly to standard, unlink them or add a convenient shortcut.
Granted, that is my personal opinion.

**Comment by dcousens** [comment]
Personally, I actually feel `unused` could have stayed, if your local tests are tied directly to standard, unlink them or add a convenient shortcut.

In pbkdf2-compat I use [two different test targets](https://github.com/crypto-browserify/pbkdf2-compat/blob/master/package.json#L16-L17) to avoid this situation.
Granted, that is my personal opinion.

**Comment by feross** [comment]
Okay, after an in-depth [discussion](https://botbot.me/freenode/webtorrent/2015-01-28/?tz=America/Los_Angeles) on IRC with folks, we've decided to:

- Re-add the rule to disallow unused variables. [https://github.com/feross/standard/commit/8134d23c8fab6d05acc2328bf4108caf2bd5e7e5] 

It turns out that this rule actually does catch pretty serious errors. Case in point, it just caught [this craziness](https://github.com/feross/bittorrent-dht/blob/a12735875febc72069256e47c14c7b89495656a2/test/basic.js#L185) in one of my own modules. We couldn't come up with a legitimate reason why an unused variable should ever stick around.

- Remove the exceptions for mocha's `describe` and `it` globals. [https://github.com/feross/standard/commit/7695e2b4f656c082d1f3074d110dcf59506b2de4]

If you use mocha, you can explicitly allow `describe` and `it` with a `/* global describe, it */` comment at top of each test file. This is a better solution than assuming these globals are always defined across all files. Also, mocha actually defines a bunch of other globals like `beforeEach`, etc. and this would have been a slippery slope.

**Comment by feross** [comment]
These changes were released as 2.0.0, along with other improvements like [adding ESLint](https://github.com/feross/standard/commit/3afa5e5dfe8578f161092291a1f4e42a56ef164c).

**Comment by jprichardson** [comment]
> undef: prevent using a variable that was never defined. Ex: myvar is used, but was never undefined.
unused: prevent defined a variable and never using it. Ex: myVar is defined, but was never used.

You won't find any disagreement from me whether these can help improve our code. My position was centered around two things:

1. This module presented itself to be more concerned with style than semantics. As far as I can tell, this was the stated intention. One can infer it from the statement: "one standard style to rule them all".
2. It's much easier to add things than to remove them. i.e. Being overzealous in the beginning may have disastrous consequences in the long run. As we may find that some of these choices may really hinder our development. I'm more in favor of limited decisions and having the rest come organically as they make sense.

That being said, I wasn't aware that I could declare globals at the top of the file via a comment. I actually really like that. Also, I didn't consider that I can just have a `npm test` with `standard && mocha` and just run `mocha` while doing actual development. When I'm ready to commit, I can verify that everything works by running `npm test` before I commit. 

All in all, I'm happy to embrace it and am excited to just tell people, committers, etc to "just use standard JavaScript" :)

**Comment by feross** [comment]
Sweet, glad that you agree with the changes!

> It's much easier to add things than to remove them

Actually, I think the reverse is true. If we add a rule, we have to bump the major version because we might cause someone's build to suddenly start failing.

If you add `standard` to a new or existing project and find that one of the rules is super tedious, we can easily just remove it. That would only be a minor version bump.
